from snakemake.utils import min_version, validate

min_version("6.0")


configfile: "config/config.yaml"


validate(config, "schemas/config.schema.yaml")


rule all:
    input:
        multiext(
            "resources/ensembl/genome",
            ".fa.gz",
            ".gtf.gz",
        ),
        "resources/ensembl/star_genome",


include: "rules/common.smk"
include: "rules/download_reference.smk"
include: "rules/ensembl_releases.smk"
include: "rules/mapping_index.smk"
