from snakemake.utils import min_version, validate

min_version("6.0")


configfile: "config/config.yaml"


validate(config, "schemas/config.schema.yaml")


include: "rules/common.smk"
include: "rules/download_reference.smk"
include: "rules/download_variants.smk"
include: "rules/gffutils.smk"
include: "rules/mapping_index.smk"
include: "rules/rseqc.smk"
include: "rules/cds_regions.smk"
include: "rules/mane_annotations.smk"

rule all:
    input:
        get_all_inputs(),