from snakemake.utils import min_version

min_version("5.0")


configfile: "config/config.yaml"


container: "docker://continuumio/miniconda3:4.10.3"


rule all:
    input:
        multiext(
            "resources/{0}/genome".format(config["ref"]["species"]),
            ".fa",
            ".fa.fai",
            ".gtf",
        ),
        "resources/{0}/star_genome".format(config["ref"]["species"]),


include: "rules/download.smk"
include: "rules/ensembl_releases.smk"
include: "rules/mapping_index.smk"
