version: '3.2'

volumes:
  snakemake-cache:
  conda-envs:

services:
  workflow:
    build: .
    container_name: reference_genomes
    volumes:
      - snakemake-cache:/mnt/snakemake-cache
      - conda-envs:/mnt/conda
      - ./workflow:/usr/src/code/workflow
