$schema: "http://json-schema.org/draft-06/schema#"

description: Snakemake configuration file for a reference genome workflow

type: object

properties:
  ref:
    title: Reference genome object
    description: Object with information about the Ensembl reference genome
    type: object

    properties:
      species:
        title: Reference genome species
        description: The species to get the Ensembl reference genome for
        examples:
          - homo_sapiens
          - mus_musculus
        type: string

    required:
      - species

required:
  - ref
