name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--use-conda --show-failed-logs --cores all --conda-cleanup-pkgs cache --all-temp --configfile .test/integration/caenorhabditis_elegans/config.yaml"

      - name: Test report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--report report.zip --configfile .test/integration/caenorhabditis_elegans/config.yaml"
